### ISSUE TITLE
relabel fail

### ISSUE THREAD

**Issue by happinesslijian** [utkuozdemir/nvidia_gpu_exporter#97]
**Problem Description：**
Before relabeling, the instance I got was like this: 192.168.1.1:9835 which contains port :9835. Whenever an alarm is triggered, it carries: 9835 port information, because it is not very beautiful, so I try to use relabel. After I relabel, I found that all the original instances will not be overwritten, which leads to the pre-relabel and The data after relabel coexists! This is a very serious bug. I don't know if something was missed during the development of nvidia_gpu_exporter, so I submitted an issue. I tried to do the same with the officially maintained node_exporter, and found that after relabeling, the data before relabeling would be replaced. The two will not coexist. Below is my relabel configuration file:
```
relabel_configs:
   - action: replace
     source_labels: [__address__]
     regex: (.*):(.*)
     replacement: $1
     target_label: instance
```
